### 1. Difference Between list & Tuple

### 2. a=(1,2,3,4) tuple elements.. what to change the index 3rd values (i,e 3) to 10


In [1]:
## No direct way, but have a work around

In [1]:
a = (1,2,3,4)
#convert to lists
a = list(a)

print(type(a))
print(a)
a[2] = 10
a = tuple(a)
print(a)
print(type(a))

<class 'list'>
[1, 2, 3, 4]
(1, 2, 10, 4)
<class 'tuple'>


#### Tuple concatination

In [2]:
b = (5,6,7, 1)
c = a + b
c

(1, 2, 10, 4, 5, 6, 7, 1)

### 3. list comprehension in python.

a. List comprehension is an elegant way to define and create lists based on existing lists.
b. List comprehension is a complete substitute for the lambda function as well as the functions map(), filter() and reduce().

In [19]:
num_list = [y for y in range(100) if y % 2 == 0 and y % 5 == 0]
print(num_list)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [1]:
squares = {x:x**2 for x in range(10, 20)}
print(squares)

{10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361}


In [8]:
squares_list = [x for x in range(2,10)]
print(squares_list)

[2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
num_list = [y for y in range(10) if y > 2 if y < 9]
print(num_list)

[3, 4, 5, 6, 7, 8]


# Generators

### 4. what is generators and iterators

A generator is a function that returns an object (iterator) which we can iterate over (one value at a time)

The difference between yield and return is that yield returns a value and pauses the execution while maintaining the internal states, whereas the return statement returns a value and terminates the execution of the function.

In [9]:
def topten():
    n = 2    
    while n < 10:
        y = n * n
        n +=1
        yield y
    
values = topten()

print(next(values))
print(next(values))

print(next(values))
print(next(values))
print(next(values))
print(next(values))
print(next(topten()))
print(next(topten()))



4
9
16
25
36
49
4
4


In [27]:
def mygenerator():
    print('First item')
    yield 10

    print('Second item')
    yield 20

    print('Last item')
    yield 30

In [5]:
gen = mygenerator()
print(next(gen))
print(next(gen))

First item
10
Second item
20


### 5. how do you define the global variable in python.


Using global keyword we can create a global variable inside a function.
Variables that are created outside of a function are known as global variables. It canbe accessble by both outside and inside function.

### 6. what is slicing and to which are all data types that it supports

In [6]:
a = ("a", "b", "c", "d", "e", "f", "g", "h")
x = slice(2,5)
print(x)
print(a[x])

slice(2, 5, None)
('c', 'd', 'e')


In [7]:
a1 = ("a", "b", "c", "d", "e", "f", "g", "h")
a1[2:5]

('c', 'd', 'e')

In [20]:
# String slicing 
String ='GeeksforGeeks'
s1 = slice(2, 15) 
s2 = slice(2, 15, 2) 
print("String slicing") 
print(String[s1]) 
print(String[s2])
print(String[1:5])

String slicing
eksforGeeks
esoGes
eeks


In [16]:
print(String[1:3])

ee


In [21]:
print(num_list)

[3, 4, 5, 6, 7, 8]


In [22]:
print(num_list[2:4])

[5, 6]


In [18]:
student = {'name':'Karthik','age':30,'courses':['Maths','Science']}
student

{'name': 'Karthik', 'age': 30, 'courses': ['Maths', 'Science']}

In [15]:
student

{'name': 'Karthik', 'age': 30, 'courses': ['Maths', 'Science']}

### 7. regex to find a valid IP adress ex: 10.0.15.81 is valid 10.123.324.888 is invalid

#### Match valid IP address

In [16]:
import re
ip1 = "10.000.110.81"
ip2 = "10.123.324.888"
        
regex = "^10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$"

if (re.search(regex, ip1)):
    print("Valid IP")
else:
    print("Invalid IP")


Valid IP


In [18]:
import re

mail = "karthik@gmail.com"
mail_2 = "Karthik@gmail.co.in.orf"

#regex = "^([A-Za-z])+[A-Za-z0-9_]*\@[A-Za-z]{2}\.[a-zA-Z]{2}$"
          #[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+

regex = "^([a-zA-Z])+[a-zA-Z0-9_]*\@[a-z]+\.[a-zA-Z.]+$"
if (re.search(regex, mail_2)):
    print("Valid mail address")
else:
    print("Invalid mail address")

Valid mail address


#### Pattern for indian phone number

In [29]:
#Phone number matach
num1 = "+9196113666120"
num2 = "00611366612"
num3 = "9611366612"

regex = "^(\+91|0)*([1-9])+[0-9]+$"

if (re.search(regex, num2)):
    print("Valid number")
else:
    print("Invalid number")

Valid number


In [18]:
#### Pattern for Email address

In [30]:
email = "dkdon@gmail.coms"
email = "d@gmail.com.in"

regex = "^([a-zA-Z])+[a-zA-Z0-9_]*\@[a-z]+\.[a-z.]+$"


if (re.search(regex, email)):
    print("Valid number")
else:
    print("Invalid number")

Valid number


### 8. a list having [1,2,3,4,5,6,7,8,9] to print the odd numbers out of it.


In [1]:
num = [1,2,3,4,5,6,7,8,9]

even = [x for x in num if x % 2 == 0]
print(even)

[2, 4, 6, 8]


In [2]:
even[::-1]

[8, 6, 4, 2]

In [37]:
num = [1,2,3,4,5,6,7,8,9]

odd = [x for x in num if x % 2 == 1]
print(odd)

[1, 3, 5, 7, 9]


### 9. possible palindromes in a string .. ex: abcdcdc o/p 4 possiblitities : cdc,dcd,cdc, cdcdc

In [62]:
string = "ABCDCDC"
word = "iTopiNonAvevanoNipoti"
word = "ABCDCDC"

polidrome_list = []
init = 3

In [63]:
while init <= (len(word)):
    for x in range(len(word)):
        next = init+x
        substr = word[x:next]
        if (substr == substr[::-1] and (len(substr) >= 3)):
            print(substr)
            polidrome_list.append(substr) 
    init +=2    
print(polidrome_list)            

CDC
DCD
CDC
CDCDC
CDC
CDCDC
CDC
['CDC', 'DCD', 'CDC', 'CDCDC', 'CDC', 'CDCDC', 'CDC']


In [64]:
str1 = "ABCDCDC"
print("string length ", len(str1))
palind = []
inits = 3
while inits <= len(str1):    
    for i in range(len(str1)):    
        nexts = i + inits
        substr = str1[i:nexts]
        # print("The substr is ", substr , " and reverse substr is ", substr[::-1])
        if (substr == substr[::-1]) and (len(substr) >= 3) and (nexts <= len(str1)):
            palind.append(substr)     
            print("found it", substr)
    inits += 2


print(palind)


string length  7
found it CDC
found it DCD
found it CDC
found it CDCDC
['CDC', 'DCD', 'CDC', 'CDCDC']


In [3]:
x = "ABCDCDC"
palin=[]
for i in range(len(x)):
    new=""
    y = x[i:]
    for j in range(len(y)):
        new = new + y[j]
        if j > 1:
            reverse = new[::-1]
            if new == reverse:
                palin.append(new)
print(palin)

['CDC', 'CDCDC', 'DCD', 'CDC']


### 10. print the row as column and column as row matrix [[1,2,3],[4,5,6],[7,8,9]] o/p : [[1,4,7],[2,5,8],[3,6,9]]


In [65]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]] 
print(matrix)

for x in matrix:
    print(x[1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2
5
8


In [66]:
import numpy as np
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]] 

matrix = np.array(matrix)
print(matrix.T)
print(matrix[0,2])


[[1 4 7]
 [2 5 8]
 [3 6 9]]
3


In [67]:
import numpy as np

a_2d = np.arange(9).reshape(3, 3)
print(a_2d)


a_2d_T = a_2d.T
print(a_2d_T)
# [[0 3]
#  [1 4]
#  [2 5]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [68]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
len(matrix)
#matrix[1][1]

3

In [73]:
n = 0
reshape = []
while n < len(matrix):
    temp_list = []
    for i in matrix:
        temp_list.append(i[n]) 
        # print(temp_list)
    reshape.append(temp_list)
    n += 1    
print(reshape)    

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [74]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
list_ex = []
list_ex.append(list1)
list_ex.append(list2)
list_ex.append(list3)


list_ex

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
list_ex
np.transpose(list_ex)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
import numpy as np
X = list([[0, 1],[2, 3]]);
np.transpose(X)  

array([[0, 2],
       [1, 3]])

### 11. to get a unique value in aq list and count of it ex; [2,45,23,1,23,45,67,45,1] o/p : [2,67]


In [11]:
dups = [2,45,23,1,23,45,67,45,1]

print(dups.count(45));
uniq = []

for i in dups:
    if dups.count(i) == 1:
        uniq.append(i)
        
    
    
print(uniq)

3
[2, 67]


In [ ]:
uniq = []
for i in dups:
    if i not in uniq:
        uniq.append(i)

uniq        

### Dictionary

### 12. print the ditctionary elements in sorted order


In [ ]:
studs = {1:'karthik', 5: 'DK', 3:'Ram', 2:'Sam'}
print((studs))

In [ ]:
for i in sorted (studs.keys()) :  
     print(i," : ", studs[i],",", end = " ") 

In [ ]:
print(sorted(studs.values()))
print(sorted(studs.keys()))

In [ ]:
str1 = "ABCDCDC"
str1[::-1]

### 13. What is decorators and give one example.


In [75]:
def shout(text):
    print (text.upper())
 
shout("Hello")
yell = shout
yell("DK")
#print(yell('Hello DK'))

HELLO
DK


In [76]:

# creating an empty list
lst = []
 
# number of elements as input
n = int(input("Enter number of elements : "))
 
# iterating till the range
for i in range(0, n):
    ele = int(input())
 
    lst.append(ele) # adding the element
     
print(lst)

Enter number of elements : 3
1
2
3
[1, 2, 3]


In [75]:
 def factorial(n):    
    if n == 1:
        print(n)
        return 1    
    else:
        print (n,'*', end=' ')
        return n * factorial(n-1)

In [79]:
print(factorial(5))

5 * 4 * 3 * 2 * 1
120


In [81]:
def facts(x):
    if x == 1:
        print(x)
        return x
    else:
        print(x, "-", end=" ")
        return (x * facts(x - 1))
    
facts(4)    


4 - 3 - 2 - 1


24

In [88]:
n = 10
fact = 1
fact_list = []
for i in range(1, n+1):
    fact_list.append(i)
    fact *=i

print(fact)    
print(fact_list)    

sum = reduce(lambda x, y: x+y, fact_list)
print(sum)

3628800
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55


In [ ]:
fact_list = range

### 14. using reduce function to print sum of factorial of each element in a list.


In [84]:
from functools import reduce

In [82]:
n=5
n = int(input("Enter the number\n"))
starts = 1
fact_list = []
while starts <= n:  
    factorial = 1
    for i in range (1,int(starts)+1):
        factorial = factorial * i
    print("Factorail of ",i , " is : ",factorial)
    fact_list.append(factorial)
    starts +=1
print(fact_list)  

sums = reduce(lambda x,y : x + y, fact_list)
print(sums)

Enter the number
5
Factorail of  1  is :  1
Factorail of  2  is :  2
Factorail of  3  is :  6
Factorail of  4  is :  24
Factorail of  5  is :  120
[1, 2, 6, 24, 120]
153


### 15. Static method and class method difference


### 16. Reverse the words of given string without using split and regular expression e.g. : "India Is An awesome Country" => "Country Awesome An Is Country"


In [4]:
string = "India Is An awesome Country"

string_list = string.split(" ")
print(string_list)
string_list.reverse()
print(string_list)

rev_strin = " ".join(string_list)
print(rev_strin)
#print(list(reversed(string_list)))
print(string)

['India', 'Is', 'An', 'awesome', 'Country']
['Country', 'awesome', 'An', 'Is', 'India']
Country awesome An Is India
India Is An awesome Country


In [1]:

string = "India Is An awesome Country"

str_list = string.split()
print(str_list)

rev_string = ""
n = len(str_list) -1
while 0 <= n:
    rev_string += str_list[n]
    rev_string += " "
    n -= 1
    
print(rev_string)

['India', 'Is', 'An', 'awesome', 'Country']
Country awesome An Is India 


In [2]:
print(str_list)
rev_str = []
for x in range(-1,-6, -1):
    rev_str.append(str_list[x])
    
    
print(rev_str)

rev_string1 = " ".join(rev_str)

print(rev_string1) 
   

['India', 'Is', 'An', 'awesome', 'Country']
['Country', 'awesome', 'An', 'Is', 'India']
Country awesome An Is India


### 17. Find the number of substring "CDC" in "ABCDCDC"


In [ ]:
dd

In [93]:
str1 = "ABCDCDC"

str1.find("CDC")

palind = []
words = [3,5,7]
inits = 3
while inits <= len(str1):    
    print(inits)
    for i in range(len(str1)):    
        nexts = i + inits
        substr = str1[i:nexts]
        if (substr == substr[::-1]) & (len(substr) >= 3) & (nexts <= len(str1)):
            palind.append(substr)             
    inits += 2


print(palind)

3
5
7
['CDC', 'DCD', 'CDC', 'CDCDC']


In [35]:
str1 = "ABCDCDC"

str1.find("CDC")
str1 = "ABCDCDC"
count = 0


i = 0
while i <= 7:
    starts = 0
    ends = 3
    starts += i
    ends += i
    temp_str = str1[starts:ends]
    if temp_str == "CDC":
        count += 1
    i += 1
print(count)    

2


### 18.File Handling: Difference between readlines and read, seek, tell method


In [ ]:
Readline == only one line
read = entire open file
seek == move the file pointer
tell = will tell current position of the pointer

### 20.  How to add any string on particular position in the given word e.g.: Add "And" in  "AweSome" => AweAndSome

In [39]:
string = "AweSome"
add_string = "And"

str_list = list(string)
print(str_list)
str_list.insert(3,add_string)
print(str_list)
string = "".join(str_list)
print(string)

string = "AweSome"
string[:3]+add_string+string[3:]

for i in string:
    print(i)

['A', 'w', 'e', 'S', 'o', 'm', 'e']
['A', 'w', 'e', 'And', 'S', 'o', 'm', 'e']
AweAndSome
A
w
e
S
o
m
e


In [ ]:
string = "I LOve india"

string[]

## Lambda Functions

#### Lambda is a anonymous function. It can take any number of arguments but only one expressions. we can invoke Lambda inside a function. 

In [ ]:
from functools import reduce

In [41]:
multi = lambda x : x*2
y = 8
multi(y)

16

In [45]:
o_list = [1,3,5,7,9]
mapping = list(map(lambda x: x-3, o_list))
print(mapping)

[-2, 0, 2, 4, 6]


In [52]:
filter = list(filter(lambda x>2, o_list))
print(filter)

SyntaxError: invalid syntax (<ipython-input-52-9b521c68f994>, line 1)

In [42]:
y = [2,4,6,8]
multi = list(map(lambda x : x*2, y))
multi

[4, 8, 12, 16]

In [51]:
y = [2,4,6,8]
multi = list(filter(lambda x : x<4, y))
multi

TypeError: 'list' object is not callable

In [ ]:
y = [2,4,6,8]
multi = reduce(lambda x, a: x+a, y)
multi

## Excel Parsing

In [ ]:
import xlrd

loc = ("/Users/devuser/Desktop/STPS_Details.xlsx") 
  
wb = xlrd.open_workbook(loc) 
sheet = wb.sheet_by_index(0) 
sheet.cell_value(0, 0) 
  
for i in range(sheet.nrows): 
    pass
   # print(sheet.cell_value(i, 1)) 

for j in range(sheet.ncols):
    print(sheet.cell_value(0,j))

In [ ]:
print(sheet.row(2))

In [ ]:
print(sheet.col(2))

In [31]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]] 
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [33]:
np.max(matrix)

9

In [10]:
X = [[4,3,8],
     [9,5,1],
     [2,7,6]]
X

[[4, 3, 8], [9, 5, 1], [2, 7, 6]]

In [11]:
import numpy as np

In [12]:
X.max()

AttributeError: 'list' object has no attribute 'max'

In [9]:
 a = set(int(input()));
A = set(input().split())

KeyboardInterrupt: Interrupted by user

In [45]:
def solution(S):
    # write your code in Python 3.6
    
    if 'b' not in S:
        return True

    if 'a' not in S:
        return True

    i = 0
    for x in S:
        #print("string is ", x)
        if x == 'a' and (i == 0 or i == 2):
            print("string is ", x)
            if i == 0:
                i = 1
            if i == 2:
                return False        
        if x == 'b':
            print("string is ", b)
            i = 2            
    if i == 2:
        return True
    
    
solution('sabb') 

string is  a


NameError: name 'b' is not defined

In [56]:
def solution(S):
    # write your code in Python 3.6
    
    if 'a' not in S:
        return True

    if 'b' not in S:
        return True

    i = 0
    for x in S:
        print("string is ", x)
        if x == 'a' and (i == 0 or i == 2):
            if i == 0:
                i = 1
            if i == 2:
                return False        
        if x == 'b':
            i = 2            
    if i == 2:
        return True
    
    
solution('sacbb') 

string is  s
string is  a
string is  c
string is  b
string is  b


True

In [57]:
def solution(S):
    if 'a' not in S:
        print("True")
        return True
    if 'b' not in S:
        print("True")
        return True
        
    i = "yes"
    
    for x in S:
        print(x)
        if x == 'a' and (i == "Yes" or i == "No"):
            if i == "Yes":
                pass
            if i == "No":
                return False
        if x == 'b':
            i = "No"
    if i == "No":
        return True
    
    
solution("aabcbb")    
            

a
a
b
c
b
b


True

In [34]:
b = "Hello, World!"
print(b[2:])
print(b[2:5])

llo, World!
llo


In [43]:
str = "Hello world"
print(str[-1:])

d


In [49]:
str.replace(" ", " * ")

'Hello * world'

In [52]:
str_list = str.split(" ")
print(str_list)

['Hello', 'world']


In [55]:
"-".join(str_list)

'Hello-world'

In [1]:
from array import *

T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

print(T[0])

print(T[1][2])

[11, 12, 5, 2]
10


In [7]:
import numpy as np
my_list = [[2,4,6,8,10],[1,2,3,4,5]]
my_array = np.array(my_list)
# printing my_array
print(my_array)
# printing the type of my_array
print (type(my_array))

[[ 2  4  6  8 10]
 [ 1  2  3  4  5]]
<class 'numpy.ndarray'>


In [1]:
list1 = [3,4,5,2,1,0]

In [4]:
list1.pop()


1

In [5]:
print(list1)

[3, 4, 5, 2]


In [10]:
"Hello World"[::-1]


'dlroW olleH'

In [11]:
func = lambda a, b : (a ** b)

In [13]:
func(float(10),20)

1e+20

In [18]:
i = ['s', 'r', 'a', 's']
j = ['a', 'a', 'n', 'h']

In [25]:
["".join([i, j]) for i, j in zip(list1, list2)]

['sa', 'ra', 'an', 'sh']

In [23]:
print(list3)

sras


In [26]:
for i, j in zip(list1, list2):
    print(i, j)

s a
r a
a n
s h


In [1]:
import datetime as datetime
import time as time
time.time()

1633429180.2212439

In [51]:
import pandas as pd
import numpy as np
series_data = pd.Series(np.random.randint(1, 20, 7))

In [52]:
series_data

0    11
1    12
2    13
3    12
4     3
5    10
6    11
dtype: int64

In [40]:
np.search(series_data % 5)


AttributeError: module 'numpy' has no attribute 'search'

In [53]:
np.argwhere(series_data % 5==0)


array([[5]])

In [47]:
np.locate(series_data % 5)

AttributeError: module 'numpy' has no attribute 'locate'

In [57]:
num1 = "1"
print(num1)
print(type(num1))

1
<class 'str'>


In [56]:
print(num1+2)

TypeError: can only concatenate str (not "int") to str

In [58]:
isinstance(num1)

TypeError: isinstance expected 2 arguments, got 1

In [80]:
# importing "array" for array creations
import array as arr
 
# creating an array with integer type
a = arr.array('i', [1, 2, 3])
 
# printing original array
print ("The new created array is : ", end =" ")
for i in range (0, 3):
    print (a[i], end =" ")
print()

The new created array is :  1 2 3 


In [36]:
def mygenerator():
    print('First item')
    yield 10

    print('Second item')
    yield 20

    print('Last item')
    yield 30

In [38]:
gen = mygenerator()


In [39]:
from collections import Counter
len(list(Counter(gen)))

First item
Second item
Last item


3

In [5]:
print(next(gen))

Last item
30


In [13]:
for i in range(1,4):
    print(next(gen))

First item
10
Second item
20
Last item
30


In [65]:

# creating an empty list
lst = []
 
# number of elements as input
n = int(input("Enter number of elements : "))
 
# iterating till the range
for i in range(0, n):
    ele = int(input())
 
    lst.append(ele) # adding the element
     
print(lst)

Enter number of elements : d


ValueError: invalid literal for int() with base 10: 'd'

##### JSON VS Dictionary

If you have a JSON string, you can parse it by using the json.loads() method.


from JSON to Dictionary ==json.load("json_string")


from Dictionary to JSON ==json.dumps("dictionary")
