#### Convert python list into numpy array.

In [61]:
import numpy as np

In [12]:

list1 = [1,2,3,4]
print(list1)

[1, 2, 3, 4]


In [13]:
my_array1 = np.array(list1)

In [14]:
my_array1

array([1, 2, 3, 4])

In [15]:
type(my_array1)

numpy.ndarray

In [27]:
list2 = [11,22,33,44]

In [28]:
lists = [list1, list2,[5,10,15,20]]

In [29]:
lists

[[1, 2, 3, 4], [11, 22, 33, 44], [5, 10, 15, 20]]

In [30]:

my_array2 = np.array(lists)

In [31]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [ 5, 10, 15, 20]])

In [32]:
my_array2.shape

(3, 4)

In [73]:
type(my_array2)

numpy.ndarray

In [74]:
 my_array2.dtype

dtype('int64')

In [75]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
np.arange(5,105,3)

array([  5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,  41,
        44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,
        83,  86,  89,  92,  95,  98, 101, 104])

# Arrays and Scalars

In [34]:
5/2
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [ 5, 10, 15, 20]])

In [35]:
my_array2 * my_array2

array([[   1,    4,    9,   16],
       [ 121,  484, 1089, 1936],
       [  25,  100,  225,  400]])

In [36]:
my_array2 - my_array2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [62]:
my_array2 - my_array2


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
1/my_array2


array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.09090909, 0.04545455, 0.03030303, 0.02272727],
       [0.2       , 0.1       , 0.06666667, 0.05      ]])

In [39]:
my_array2 * 10

array([[ 10,  20,  30,  40],
       [110, 220, 330, 440],
       [ 50, 100, 150, 200]])

# Array Indexing

In [43]:
arr = np.arange(5,10)

In [44]:
arr

array([5, 6, 7, 8, 9])

In [45]:
arr[1]

6

In [46]:
arr[0]

5

In [47]:
print(arr[0:4])

[5 6 7 8]


In [48]:
arr[0:4] = 100

In [49]:
arr

array([100, 100, 100, 100,   9])

In [50]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [51]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[1][0]

20

In [64]:
arr_2d[0,1]

10

In [65]:
arr_2d[1:2,1:3]

array([[25, 30]])

In [66]:
arr_2d[0:1,1:3]

array([[10, 15]])

In [67]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])