# Numpy - Numerical Python

In [1]:
import numpy as np

In [3]:
# Numpy Array   int(4.5)
a = np.array([2,5,7])
type(a)

numpy.ndarray

In [5]:
print(a)

[2 5 7]


In [9]:
#homogeneous
a = np.array([2,5.5,7,True,'hello'])
print(a)

['2' '5.5' '7' 'True' 'hello']


In [17]:
#homogeneous
a = np.array([2,5,7])
print(a)
print("size of the array : ",a.size)
print("Array element datatype : ",a.dtype)
print("Number of dimension : ",a.ndim)
print("shape of the Array : ",a.shape)

[2 5 7]
size of the array :  3
Array element datatype :  int64
Number of dimension :  1
shape of the Array :  (3,)


In [18]:
#homogeneous
# 2-D array is a collection 1-D arrays
a = np.array([ 
                [2,5,7],
                [6,9,3]
             ])
print(a)
print("size of the array : ",a.size)
print("Array element datatype : ",a.dtype)
print("Number of dimension : ",a.ndim)
print("shape of the Array : ",a.shape)

[[2 5 7]
 [6 9 3]]
size of the array :  6
Array element datatype :  int64
Number of dimension :  2
shape of the Array :  (2, 3)


In [20]:
#homogeneous
# 3-D array is a collection 2-D arrays
a = np.array([
             [ [2,5,7],
                [6,9,3]],
             [ [4,15,17],
                [61,19,32]]
            ])
print(a)
print("size of the array : ",a.size)
print("Array element datatype : ",a.dtype)
print("Number of dimension : ",a.ndim)
print("shape of the Array : ",a.shape)

[[[ 2  5  7]
  [ 6  9  3]]

 [[ 4 15 17]
  [61 19 32]]]
size of the array :  12
Array element datatype :  int64
Number of dimension :  3
shape of the Array :  (2, 2, 3)


In [24]:
# insistant int array becomes array of lists
# 3-D array is a collection 2-D arrays
a = np.array([ [2,3,7], [7,3] ])
print(a)
print("size of the array : ",a.size)
print("Array element datatype : ",a.dtype)
print("Number of dimension : ",a.ndim)
print("shape of the Array : ",a.shape)

[list([2, 3, 7]) list([7, 3])]
size of the array :  2
Array element datatype :  object
Number of dimension :  1
shape of the Array :  (2,)
