# Basics of Numpy - Numerical Python

In [1]:
import numpy as np

In [5]:
#Numpy Array
# its a homegeneou.
a = np.array([2,5,7]) # int(4.5) kind of convert a python list into numpy array.
type(a)

numpy.ndarray

In [4]:
print(a)

[2 5 7]


In [12]:
a = np.array([2,5,7, 'True'])
print(a)
print(a.dtype)

['2' '5' '7' 'True']
<U21


In [8]:
a = np.array([2,5,7.6])
print(a)

[2.  5.  7.6]


In [14]:
# a is an Numpy Array object
a = np.array([2,5,7]) 
print ("Size of the array is : ", a.size)
print ("Array element datatype is : ", a.dtype)
print ("Number of dimentsion is : ", a.ndim)
print ("Shape of array is : ", a.shape)

Size of the array is :  3
Array element datatype is :  int64
Number of dimentsion is :  1
Shape of array is :  (3,)


In [21]:
# a is an Numpy Array object
# 2- D array is collection of 1-D arrays
a = np.array([
                [2,5,7],
                [6,9,3],
                [1,2,3]
            ]) 
print ("Size of the array is : ", a.size)
print ("Array element datatype is : ", a.dtype)
print ("Number of dimentsion is : ", a.ndim)
print ("Shape of array is : ", a.shape)

Size of the array is :  9
Array element datatype is :  int64
Number of dimentsion is :  2
Shape of array is :  (3, 3)


### 3- Dimension Array

In [30]:
# a is an Numpy Array object
# 2- D array is collection of 1-D arrays
a = np.array([
              [[2,5,7],
                [6,9,3]],
    
                [[11,12,13],
                 [14,15,16]]
            ]) 
print(a)
print ("Size of the array is : ", a.size)
print ("Array element datatype is : ", a.dtype)
print ("Number of dimentsion is : ", a.ndim)
print ("Shape of array is : ", a.shape)

[[[ 2  5  7]
  [ 6  9  3]]

 [[11 12 13]
  [14 15 16]]]
Size of the array is :  12
Array element datatype is :  int64
Number of dimentsion is :  3
Shape of array is :  (2, 2, 3)


In [44]:
#2,3,4,5
b = np.array([
    
            [
              [[2,5,7,4,5],
               [6,9,3,4,5],
               [2,5,7,4,5],
               [2,5,7,4,5]],
    
               [[11,12,13,4,5],
                [14,15,16,4,5],
                [14,15,16,4,5],
                [14,15,16,4,5]],
                
                [[11,12,13,4,5],
                [14,15,16,4,5],
                [14,15,16,4,5],
                [14,15,16,4,5]]
            ],
    
            [
              [[2,5,7,4,5],
               [6,9,3,4,5],
               [6,9,3,4,5],
               [6,9,3,4,5]],
    
               [[11,12,13,5,4],
                [11,12,13,5,4],
                [11,12,13,5,4],
                [14,15,16,4,5]],
                
                [[11,12,13,5,4],
                [11,12,13,5,4],
                [11,12,13,5,4],
                [14,15,16,4,5]]
            ]
]) 

print(b)

[[[[ 2  5  7  4  5]
   [ 6  9  3  4  5]
   [ 2  5  7  4  5]
   [ 2  5  7  4  5]]

  [[11 12 13  4  5]
   [14 15 16  4  5]
   [14 15 16  4  5]
   [14 15 16  4  5]]

  [[11 12 13  4  5]
   [14 15 16  4  5]
   [14 15 16  4  5]
   [14 15 16  4  5]]]


 [[[ 2  5  7  4  5]
   [ 6  9  3  4  5]
   [ 6  9  3  4  5]
   [ 6  9  3  4  5]]

  [[11 12 13  5  4]
   [11 12 13  5  4]
   [11 12 13  5  4]
   [14 15 16  4  5]]

  [[11 12 13  5  4]
   [11 12 13  5  4]
   [11 12 13  5  4]
   [14 15 16  4  5]]]]


In [42]:
print ("Size of the array is : ", b.size)
print ("Array element datatype is : ", b.dtype)
print ("Number of dimentsion is : ", b.ndim)
print ("Shape of array is : ", b.shape)

Size of the array is :  120
Array element datatype is :  int64
Number of dimentsion is :  4
Shape of array is :  (2, 3, 4, 5)


In [45]:
print ("Number of dimentsion is : ", b.ndim)


Number of dimentsion is :  4


In [70]:
b = np.array([[[[1,2,3,4]]]])
print ("Size of the array is : ", b.size)
print ("Array element datatype is : ", b.dtype)
print ("Number of dimentsion is : ", b.ndim)
print ("Shape of array is : ", b.shape)

Size of the array is :  4
Array element datatype is :  int64
Number of dimentsion is :  4
Shape of array is :  (1, 1, 1, 4)


### Array Range

In [54]:
a = np.arange(10)
print(a)
print ("Size of the array is : ", a.size)
print ("Array element datatype is : ", a.dtype)
print ("Number of dimentsion is : ", a.ndim)
print ("Shape of array is : ", a.shape)

[0 1 2 3 4 5 6 7 8 9]
Size of the array is :  10
Array element datatype is :  int64
Number of dimentsion is :  1
Shape of array is :  (10,)


In [56]:
a = np.arange(120)
a = a.reshape(2,3,4,5)
print(a)
print ("Size of the array is : ", a.size)
print ("Array element datatype is : ", a.dtype)
print ("Number of dimentsion is : ", a.ndim)
print ("Shape of array is : ", a.shape)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
Size of the array is :  120
Array element datatype is :  int64
Number of dimentsion is :  4
Shape of array is :  (2, 3, 4, 5)


## Force Type Casting

In [61]:
a = np.array([2,3,4,5], dtype ='float')
print(a)
print(a.dtype) 
a = np.array([2,3,0,-5,'hello'], dtype ='bool')
print(a)
print(a.dtype) 

[2. 3. 4. 5.]
float64
[ True  True False  True  True]
bool


In [62]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [65]:
np.arange(10,20,3) # start, end, step

array([10, 13, 16, 19])

### Linear Space Linspace

In [67]:
np.linspace(10,20,3) # start, end, no of element equally distribute

array([10., 15., 20.])

In [68]:
np.linspace(10,20,8)

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])

### Random Numbers
#numpy functions apply to whole array

In [73]:
#Rand()
np.random.rand()

0.7369756870121785

In [76]:
np.random.rand(4)*100

array([59.56930534, 99.87670375, 71.45357402, 32.91403464])

In [77]:
np.round(np.random.rand(4)*100)

array([45., 52., 28., 67.])

In [78]:
np.floor(np.random.rand(4)*100)

array([51., 30., 77.,  5.])

In [79]:
np.ceil(np.random.rand(4)*100)

array([16., 90., 52., 28.])

In [82]:
print(np.round(10.8))
print(np.floor(10.8))
print(np.ceil(10.8))

11.0
10.0
11.0


In [86]:
# Generate random numbers 200 between 35 and 100
int (35 + np.random.rand()*(100-36))

85

In [95]:
np.random.randint(35,100, 10)

array([43, 42, 71, 97, 99, 93, 64, 37, 84, 99])

In [96]:
# Random number generation is very usefull in sample space creation for model evaluations

In [110]:
np.sqrt(np.random.randint(35,100, 20).reshape(4,5))

array([[7.87400787, 7.14142843, 7.48331477, 6.55743852, 6.32455532],
       [9.43398113, 9.59166305, 8.77496439, 9.11043358, 7.34846923],
       [7.48331477, 8.24621125, 9.59166305, 7.81024968, 6.4807407 ],
       [7.87400787, 9.94987437, 6.92820323, 8.1240384 , 7.68114575]])

In [116]:
print(np.sqrt(25))
print(np.log(25))
print(np.exp(3))
print(np.tan(3))
print(np.pi)


5.0
3.2188758248682006
20.085536923187668
-0.1425465430742778
3.141592653589793


### Ravel is the opposite of reshape. It will flatten the multi-dimentional array into single dimentional arry

In [120]:
#can you create 6 dimensional array with 6 elements?
np.arange(6).reshape(1,1,1,1,1,6)

array([[[[[[0, 1, 2, 3, 4, 5]]]]]])

np.arange(6).reshape(1,1,1,1,2,3)

In [122]:
np.arange(6).reshape(6,1,1,1,1,1)

array([[[[[[0]]]]],




       [[[[[1]]]]],




       [[[[[2]]]]],




       [[[[[3]]]]],




       [[[[[4]]]]],




       [[[[[5]]]]]])

In [125]:
a = np.random.randint(10,200,24).reshape(4,6)
a

array([[ 83, 185, 102,  45,  58,  93],
       [ 63, 119,  46, 163,  52, 196],
       [190, 108,  50, 181,  42,  41],
       [ 19, 186, 152, 126,  19,  34]])

In [131]:
splits = np.hsplit(a,2)
print(splits)
print(splits[0])
print(splits[1])

[array([[ 83, 185, 102],
       [ 63, 119,  46],
       [190, 108,  50],
       [ 19, 186, 152]]), array([[ 45,  58,  93],
       [163,  52, 196],
       [181,  42,  41],
       [126,  19,  34]])]
[[ 83 185 102]
 [ 63 119  46]
 [190 108  50]
 [ 19 186 152]]
[[ 45  58  93]
 [163  52 196]
 [181  42  41]
 [126  19  34]]


In [132]:
splits = np.hsplit(a,3)
print(splits)
print(splits[0])
print(splits[1])

[array([[ 83, 185],
       [ 63, 119],
       [190, 108],
       [ 19, 186]]), array([[102,  45],
       [ 46, 163],
       [ 50, 181],
       [152, 126]]), array([[ 58,  93],
       [ 52, 196],
       [ 42,  41],
       [ 19,  34]])]
[[ 83 185]
 [ 63 119]
 [190 108]
 [ 19 186]]
[[102  45]
 [ 46 163]
 [ 50 181]
 [152 126]]


In [133]:
np.vsplit(a,2)

[array([[ 83, 185, 102,  45,  58,  93],
        [ 63, 119,  46, 163,  52, 196]]),
 array([[190, 108,  50, 181,  42,  41],
        [ 19, 186, 152, 126,  19,  34]])]

In [134]:
np.vsplit(a,2)[0]

array([[ 83, 185, 102,  45,  58,  93],
       [ 63, 119,  46, 163,  52, 196]])

In [135]:
np.vsplit(a,2)[1]

array([[190, 108,  50, 181,  42,  41],
       [ 19, 186, 152, 126,  19,  34]])

In [137]:
a = np.random.randint(10,200,9).reshape(3,3)
print(a)
b = np.random.randint(10,200,9).reshape(3,3)
print(b)

[[113  66 129]
 [ 54 185  90]
 [193 156  43]]
[[ 12  62 159]
 [ 75 161  74]
 [ 18  39  20]]


In [138]:
np.hstack((a,b))

array([[113,  66, 129,  12,  62, 159],
       [ 54, 185,  90,  75, 161,  74],
       [193, 156,  43,  18,  39,  20]])

In [144]:
np.vstack((a,b))

array([[9, 3],
       [1, 2],
       [4, 1],
       [1, 1]])

In [145]:
a = np.random.randint(1,20,4).reshape(2,2)
print(a)
b = np.random.randint(1,20,4).reshape(2,2)
print(b)

[[18 12]
 [ 8  5]]
[[14  1]
 [ 5  8]]


In [149]:
np.multiply(a,b)

array([[252,  12],
       [ 40,  40]])

In [148]:
np.matmul(a,b)

array([[312, 114],
       [137,  48]])

## Shallow vs Deep Copy

### Shallow Copy

In [150]:
a = [1,2,3]
b = a
print("a is :", a)
print("b is :", b)

a is : [1, 2, 3]
b is : [1, 2, 3]


In [151]:
a[1] = 5
print("a is :", a)
print("b is :", b)

a is : [1, 5, 3]
b is : [1, 5, 3]


### Deep Copy

In [154]:
a = [1,2,3]
b = a.copy()
print("a is :", a)
print("b is :", b)

## The change only effect in A not in B
a[1] = 5
print("a is :", a)
print("b is :", b)

a is : [1, 2, 3]
b is : [1, 2, 3]
a is : [1, 5, 3]
b is : [1, 2, 3]
